config/routes.rb
Rails.application.routes.draw do
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders do
    resources :orderitems
  end
  resources :categories
  get 'cart/index'
  
  get '/cart', to: 'cart#index'
  
  post '/search', to: 'products#search'
  
  get '/category/:title', to: 'static_pages#category'

  devise_for :users do
    resources :orders
  end
  
  get '/paid' => 'static_pages#paid'
  
  get '/profile' => 'static_pages#profile'
  
  get '/checkout' => 'cart#createOrder'
  
  get '/admin' => 'static_pages#admin'
  
  get '/admin/:id' => 'static_pages#admin'
  
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/products', to: 'products#index'
  
  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id', to: 'cart#remove'
    
  root :to => "site#home"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all
    @products = Product.all
  end

  def about
    
  end
  
  def category
    catName = params[:title]
    @catName = catName
    @products = Product.where("category like ? ", catName)
  end
  
  def createOrder
    @orders = Order.all
    
  end
  
  def paid
    flash[:notice] = 'Transaction Complete'
    @order = Order.last
    @order.update_attribute(:status , "Paid by User: #{current_user.email}")
  end
  
  def profile
    @user = User.find_by_id(current_user.id)
    @user_orders = Order.where(user_id: current_user.id)
    @cart = session[:cart] || {}
    @cart_count = @cart.length
    
    @total_complete = 0
    @total_pending = 0
      @user_orders.each do |order|
        if order.status != "Pending"
          @total_complete = @total_complete + 1
        else
          @total_pending = @total_pending + 1
        end
      end
  end
  
  def admin
    if params[:id]
      @user = User.find_by_id(params[:id])
      
      
      if @user.admin
        @user.admin = false
        flash[:notice] = "Admin privelages removed for: #{@user.email}"
      else
        @user.admin = true
        flash[:notice] = "Admin privelages granted for: #{@user.email}"
      end
      @user.save
      redirect_to '/admin'
    end
    
    @me = current_user
    @users = User.all
  end
end

app/views/static_pages/about.html.erb
<div class="home-container" style="min-height: 100vh;">
    
    <div class="title-container about">
        <h1>DON'T PANIC</h1>
        <h2>ABOUT</h2>
        <div class="about-container">
            
            <div class="part1">
                <p>So, you’ve been hurled into space because a fleet of Vogon ships destroyed planet earth in order 
                to create space for a hyperspace bypass…now what? <em>Whatever you do…</em></p>
                <h3>DON'T PANIC!!</h3>
                <p>In this shop you will find all the essentials you need on your journey, from the Sub-Etha Sens-O-Matic to help you 
                    hitchhike through the galaxy, to your Joo Janta 200 Super-Chromatic Peril Sensitive Sunglass, which allow you to 
                    hitchhike in style! The inspiration for this site lays in The Hitchhiker's Guide to the Galaxy (sometimes referred to as 
                    HG2G, HHGTTG), which is a series of science fiction created by Douglas Adams in 1978.
                </p>
            </div>
            <br>
            <div class="part2">
                
                <p>The Hitchhiker's Guide to the Galaxy franchise started with a radio series, and now includes books, television series, and a feature length film. 
                    A whole universe of merchandising has sprung from this saga of angst and despair--from illustrated book versions to towels. 
                    The story centres on an Earthling, Arthur Dent, one of a handful of survivors of the demolition of planet Earth by a Vogon 
                    fleet to make way for a hyperspace bypass. After the destruction of Earth, Arthur starts his travels through the galaxy with his 
                    friend Ford Prefect
                    He heavily relies on a copy of The Hitchhiker's Guide to the Galaxy, a woefully inaccurate electronic tourist guide to life, 
                    the universe and everything.
                </p>
            </div>
        </div>
        
    </div>
</div>

app/views/static_pages/admin.html.erb
<div style="background:white;">
    <h1>Users</h1>
    <table>
        <tr>
            <td>Email</td>
            <td>ID</td>
            <td>Admin</td>
            <td>Admin Privelages</td>
        </tr>
        <% @users.each do |user| %>
            <% if user.id != current_user.id %>
                <tr>
                    <td><%= user.email %></td>
                    <td><%= user.id %></td>
                    <% if user.admin %>
                        <td>Yes</td>
                        <td><a class="button" style="width: 100px; background: tomato" href="/admin/<%= user.id %>">Remove</a></td>
                    <% else %>
                        <td>No</td>
                        <td><a class="button" style="width: 100px" href="/admin/<%= user.id %>">Add</a></td>
                    <% end %>
                    
                </tr>
            <% end %>
        <% end %>
    </table>
</div>

app/views/static_pages/category.html.erb
<p id="notice"><%= notice %></p>

    <h1 style="color:#333;"><%= @catName %></h1>
    <div id="productContainer">
  
    <% if @products.length == 0 %>
        <h2>There are currently no products in this category</h2>
    <% end %>

      <% @products.each do |product| %>
      <div class="producthols">
        <h1><%= product.title %></h1>
       
        <%= link_to (image_tag product.image_url, :class => "productholsIm"), product %>
        <p><%= truncate(product.description, length: 150) %> <%= link_to '(Read More)',  product %></p>
        <div class="product-info">
          <div class="product-info-price">
            <span>
              Price
            </span> 
            <span>
              <%= number_to_currency(product.price, :unit => "€") %>
            </span>
          </div>
          <div class="product-info-category">
            <span>
              Category
            </span>
            <span>
              <%= product.category %>
            </span>
          </div>
        </div>
        <p>
          <a href="/cart/<%= product.id %>" class="button"><i class="fas fa-cart-plus"></i> Add to Cart</a>
          <%= link_to '<i class="far fa-eye"></i> Show'.html_safe,  product, :class => "button", :role => "button" %>
          <% if current_user.try(:admin?) %>
            <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe,  edit_product_path(product), :class => "button", :role => "button" %>
            <%= link_to '<i class="fas fa-trash-alt"></i> Destroy'.html_safe,  product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
          <% end %>
        </p>
        
      </div>
   
    <% end %>
      
</div>

app/views/static_pages/home.html.erb
<div class="home-container">
    
    <div class="title-container">
        <h1>DON'T PANIC</h1>
        <p>Everything you <em>need</em> to survive in the Universe</p>
    </div>
    <div class="cat-container">
        <%= render 'layouts/categories' %>
    </div>
    <div class="pop-container">
        <%= render 'layouts/popular'%>
    </div>
</div>

app/views/static_pages/paid.html.erb
<h2>Many Thanks!</h2>

app/views/static_pages/profile.html.erb
<div style="background:white;">
    <h1>User Profile</h1>
    <br>
    <h2>Hello, <%= @user.email %></h2>
    <p>It's been <%= time_ago_in_words(@user.last_sign_in_at)%> since you last logged in, we were starting to miss you!</p>
    <br>
    <div>
        
        <%= link_to "Edit User Password or Email Address", edit_user_registration_path, :class => "button" %>
    </div>
    <h2>User Info</h2>
    
    <table>
        <tr>
            <td>Sign in Count</td>
            <td>Last Sign In</td>
            <td>Created Account</td>
            <td>Orders Made</td>
            <td>Orders Completed</td>
            <td>Orders Pending</td>
            <td>Current items in cart</td>
        </tr>
        <tr>
            <td>
                <%= @user.sign_in_count  %> times
            </td>
            <td>
                <%= @user.last_sign_in_at.strftime("%A %B %d, %Y")  %>
            </td>
            <td>
                <%= @user.created_at.strftime("%A %B %d, %Y")  %>
            </td>
            <td>
                <%= @user_orders.length %>
            </td>
            <td>
                <%= @total_complete  %>
            </td>
            <td> 
                <%= @total_pending %>
            </td>
            <td>
                <%= @cart_count  %>
            </td>
        </tr>
    </table>
    
    
    
    <h2>Previous Orders</h2>
    <% if @user_orders.length == 0 %>
      <h2>You havn't ordered anything yet!</h2>
    <% else %>
    <table style="margin-bottom: 50px;">
      <thead>
        <tr>
          <th>Order date</th>
          <th>User</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @user_orders.each do |order| %>
          <tr>
            <td><%= order.order_date %></td>
            <td><%= @user.email %></td>
            <td><%= order.status %></td>
            <td><%= link_to 'Show', order, :class =>"button" %></td>
            <% if current_user.try(:admin?) %>
                <td><%= link_to 'Edit', edit_order_path(order), :class =>"button" %></td>
            <% end %>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
</div>