config/routes.rb
Rails.application.routes.draw do
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders do
    resources :orderitems
  end
  resources :categories
  get 'cart/index'
  
  get '/cart', to: 'cart#index'
  
  post '/search', to: 'products#search'
  
  get '/category/:title', to: 'static_pages#category'

  devise_for :users do
    resources :orders
  end
  
  get '/paid' => 'static_pages#paid'
  
  get '/profile' => 'static_pages#profile'
  
  get '/checkout' => 'cart#createOrder'
  
  get '/admin' => 'static_pages#admin'
  
  get '/admin/:id' => 'static_pages#admin'
  
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/products', to: 'products#index'
  
  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id', to: 'cart#remove'
    
  root :to => "site#home"

end

app/views/layouts/_categories.html.erb
<br>
<h3>Categories</h3>
<div class="productContainer">
    <div class="categories">
        <% @categories.each do |category| %>
            <div class="itemhols cat">
                <p><a href="/category/<%= category.title %>" class="button"><%= category.title %></a></p>
                <%= link_to (image_tag category.image, :class => "product-desc-img cat-img"), "category/#{category.title}" %>
                <p><%= category.description %></p>
            </div>
        <% end %>
    </div>
    
</div>

app/views/layouts/_footer.html.erb
<footer>
    <% if current_user.try(:admin?) %>
        <%= link_to 'New Category', new_category_path, :class =>"button", :role => "button" %>
        <%= link_to 'New Product',  new_product_path, :class => "button", :role => "button" %>
    <% end %>
</footer>

app/views/layouts/_header.html.erb
<div class="menu-button" id="menu-button"></div>
<div class="title">
    <h1>DON'T PANIC</h1>
</div>

<ul class="nav">
    <li class="nav-item">
        <%= link_to 'Home <i class="fas fa-home"></i>'.html_safe, root_path, :class => "nav-link" %>
        </li>
    <li class="nav-item"><%= link_to 'Products <i class="fas fa-shopping-basket"></i>'.html_safe, products_path, :class => "nav-link" %></li>
    <li class="nav-item"><%= link_to 'About <i class="fas fa-info-circle"></i>'.html_safe, about_path, :class => "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Cart <i class="fas fa-shopping-cart"></i>'.html_safe, cart_path, :class => "nav-link" %></li>
    <% if user_signed_in? %>
        <!--<li class="nav-item"><%# link_to "My Orders", orders_path, :class => "nav-link" %></li>-->
        <li class="nav-item"><%= link_to 'Profile <i class="fas fa-user"></i>'.html_safe, profile_path, :class => "nav-link" %></li>
        <% if current_user.try(:admin?) %>
            <li class="nav-item"><%= link_to 'Admin <i class="fas fa-unlock-alt"></i>'.html_safe, admin_path, :class => "nav-link" %></li>
        <% end %>
        <li class="nav-item"><%= link_to 'Log Out<i class="fas fa-sign-out-alt"></i>'.html_safe, destroy_user_session_path, :method => :delete, :class => "nav-link" %></li>
    <% else %>
        <li class="nav-item"><%= link_to 'Register <i class="fas fa-user-plus"></i>'.html_safe, new_user_registration_path, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Log In <i class="fas fa-sign-in-alt"></i> '.html_safe, new_user_session_path, :class => "nav-link" %></li>
    <% end %>
    <li class="nav-item"><%= render 'layouts/search' %></li>
    
    <!--This parts here adds a little cart information box at the end of the navigation menu-->
    <!--if there are items in the cart.-->
    <li class="nav-item">
        <% if session[:cart] %>
        
            <!--Here i get the cart session, and set a counter variable "total" to 0-->
            <% cart = session[:cart] %>
            <% total = 0 %> 
            
            <!--Here i do a loop through every item in the cart-->
            <!--For each item, i basically add the total of each item, to the total variable above-->
            <% cart.each do |id, quantity| %>
                <% product = Product.find_by_id(id) %>
                <% total += quantity * product.price %>
            <% end %>
            
            <!--Then here, i use that information to display the cart info in the site navigation-->
            <a href="/cart">
                <div class="mini-cart" style="color:white;">
                    <p>Your Cart</p>
                    <div>Items: <%= cart.length %></div>
                    <div>Total: <%= number_to_currency(total, :unit => "€") %></div>
                </div>
            </a>
        <% end %>
    </li>
</ul>

app/views/layouts/_popular.html.erb
    <h2>Popular Products</h2>
<div class="productContainer">
    <% @products.limit(2).order(:id).each do |product| %>
          <div class="producthols" style="margin-bottom: 50px;">
            <h1><%= product.title %></h1>
           
            <%= link_to (image_tag product.image_url, :class => "productholsIm"), product %>
            <p><%= truncate(product.description, length: 150) %> <%= link_to '(Read More)',  product %></p>
            <div class="product-info" style="color:#333;">
              <div class="product-info-price">
                <span>
                  Price
                </span> 
                <span>
                  <%= number_to_currency(product.price, :unit => "€") %>
                </span>
              </div>
              <div class="product-info-category">
                <span>
                  Category
                </span>
                <span>
                  <%= product.category %>
                </span>
              </div>
            </div>
            <p>
              <a href="/cart/<%= product.id %>" class="button"><i class="fas fa-cart-plus"></i> Add to Cart</a>
              <%= link_to '<i class="far fa-eye"></i> Show'.html_safe,  product, :class => "button", :role => "button" %>
              <% if current_user.try(:admin?) %>
                <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe,  edit_product_path(product), :class => "button", :role => "button" %>
                <%= link_to '<i class="fas fa-trash-alt"></i> Destroy'.html_safe,  product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
              <% end %>
            </p>
            
          </div>
       
        <% end %>
    
</div>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post", :class => "search-form") do %>
<%= text_field_tag(:q, nil, placeholder: "Search") %>
<%= submit_tag("Search", :class => "nav-link search-button") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DontPanic</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="header-container">
      <%= render 'layouts/header' %>
    </div>
    
    <div class="main-container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      
    </div>
  </body>
</html>